import { footerAct1, footerAct2 } from '../assets/base';
import {
  sticker,
  pdPd1,
  bankBn1,
  bankBn2,
  bankBn3,
  activeAct1,
  activeAct2,
  classic1,
  classic2,
  classic3,
  classic4,
  classic5,
  classic6,
  classic7,
} from '../assets/layout';
export const mockPdData = [
  {
    BlockId: 31,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '',
        productTitle: '',
        marketPrice: '',
        discountPrice: '786500',
        imgSrc: '',
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 42,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下水1',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: pdPd1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下水2',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: pdPd1,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下水3',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: pdPd1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下4',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: pdPd1,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 53,
    Nodes: [
      {
        id: 0,
        url: '',
        productName:
          '石頭掃地機S8系列品項單筆交易滿$40,000享LINE POINTS 2000點',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBn1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '下單石頭掃地機S8系列品項，現折$3,000元',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBn2,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'Pi 拍錢包綁玉山 Pi 卡，最高回饋6%',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: bankBn3,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 64,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: '搶先購新機 週週直播抽Hermès',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: activeAct1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: '下搶先購新機，曬單抽IPad',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: activeAct2,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 220,
    Nodes: [
      {
        id: 0,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下水1',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: classic1,
        imgTitle: '',
      },
      {
        id: 1,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下水2',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: classic2,
        imgTitle: '',
      },
      {
        id: 2,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下水3',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: classic3,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下4',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: classic4,
        imgTitle: '',
      },
      {
        id: 4,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下5',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: classic5,
        imgTitle: '',
      },
      {
        id: 5,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下6',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: classic6,
        imgTitle: '',
      },
      {
        id: 6,
        url: '',
        productName: 'S8 Pro Ultra + 自動上下7',
        productTitle: '',
        marketPrice: '71998',
        discountPrice: '42888',
        imgSrc: classic7,
        imgTitle: '',
      },
      {
        id: 7,
        url: '',
        productName: 'roborock',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: classic7,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 816,
    Nodes: [
      {
        id: 2,
        url: '',
        productName: '天天簽到',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct1,
        imgTitle: '',
      },
      {
        id: 3,
        url: '',
        productName: '限時瘋搶',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: footerAct2,
        imgTitle: '',
      },
    ],
  },
  {
    BlockId: 827,
    Nodes: [
      {
        id: 2,
        url: '',
        productName: '活動總覽',
        productTitle: '',
        marketPrice: '',
        discountPrice: '',
        imgSrc: sticker,
        imgTitle: '',
      },
    ],
  },
];
